.SUFFIXES:
.SECONDARY:
SHELL := /bin/bash

URL := https://archive.org/download/ps1_sdks/Programmer%20Tool%20-%20Runtime%20Library%20Version%203.5%20%28Japan%29%20%28En%2CJa%29_DTL-S2300_redump.zip

.PHONY: all
all: tarballs/psyq-35.tar.gz

tarballs/psyq-35.tar.gz: output/35
	@mkdir -p tarballs/
	tar -C $< -czf $@ .

output/35: extracted/35 wibo/build/wibo
	mkdir -p $@/BIN
	cp -r $</PSX/{LIB,INCLUDE} $@/
	cp $</PSX/BIN/DMPSX.EXE $</PSYQ/{ASMPSX,ASPSX,CCPSX,DUMPOBJ,PSYLIB,PSYLINK}.EXE $@/BIN/
	chmod a+rx $@/BIN/*
	touch $@/BIN/PSYQ.INI
	for exe in $@/BIN/*.EXE; do cp wibo/build/wibo $@/; cp wrapper.sh $@/`basename -s.EXE $$exe | tr A-Z a-z`; done

extracted/35: dl/35
	mkdir -p $@
	7z e -o$@ -i!'*Track 1*.bin' $<
	iat $@/*.bin $@/fs.iso
	-7z x -o$@ $@/fs.iso
	rename -d y/a-z/A-Z/ $@/*
	rename -d y/a-z/A-Z/ $@/*/*
	rename -d y/a-z/A-Z/ $@/*/*/*
	rm -f $@/*.bin $@/fs.iso

dl/35:
	mkdir -p dl
	wget --progress=dot:mega "$(URL)" -O $@

wibo/build/wibo:
	cmake wibo -B wibo/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0" -DCMAKE_FIND_LIBRARY_SUFFIXES=".a" -DCMAKE_EXE_LINKER_FLAGS="-static"
	make -C wibo/build

.PHONY: clean
clean:
	rm -rf extracted/35 output/35 tarballs/psyq-35.tar.gz
