.SUFFIXES:
.SECONDARY:
SHELL := /bin/bash

URL := https://archive.org/download/ps1_sdks/Programmer%20Tool%20-%20Runtime%20Library%20Version%203.6%20%28Japan%29_DTL-S2310_redump.zip

.PHONY: all
all: tarballs/psyq-36.tar.gz

tarballs/psyq-36.tar.gz: output/36
	@mkdir -p tarballs/
	tar -C $< -czf $@ .

output/36: extracted/36 wibo/build/wibo extract_news.py convert_libs.py pcsx-redux/bins/Release/psyq-obj-parser
	mkdir -p $@/BIN
	cp -r $</PSX/{LIB,INCLUDE} $@/
	./extract_news.py $</NEWS/NEWSLIB.Z $@/NEWS
	./convert_libs.py pcsx-redux/bins/Release/psyq-obj-parser $@/LIB $@/ELF
	cp $</PSX/BIN/DMPSX.EXE $</PSYQ/{ASMPSX,ASPSX,CCPSX,DUMPOBJ,PSYLIB,PSYLINK}.EXE $@/BIN/
	chmod a+rx $@/BIN/*
	touch $@/BIN/PSYQ.INI
	for exe in $@/BIN/*.EXE; do cp wibo/build/wibo $@/; cp wrapper.sh $@/`basename -s.EXE $$exe | tr A-Z a-z`; done

pcsx-redux/bins/Release/psyq-obj-parser:
	cd pcsx-redux && git submodule update --init third_party/fmt third_party/ELFIO third_party/magic_enum third_party/ucl
	$(MAKE) -C pcsx-redux bins/Release/psyq-obj-parser HAS_SUBMODULES=true

extracted/36: dl/36
	mkdir -p $@
	7z e -o$@ -i!'*Track 1*.bin' $<
	iat $@/*.bin $@/fs.iso
	-7z x -o$@ $@/fs.iso
	rename -d y/a-z/A-Z/ $@/*
	rename -d y/a-z/A-Z/ $@/*/*
	rename -d y/a-z/A-Z/ $@/*/*/*
	rm -f $@/*.bin $@/fs.iso

dl/36:
	mkdir -p dl
	wget --progress=dot:mega "$(URL)" -O $@

wibo/build/wibo:
	cmake wibo -B wibo/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0" -DCMAKE_FIND_LIBRARY_SUFFIXES=".a" -DCMAKE_EXE_LINKER_FLAGS="-static"
	make -C wibo/build

.PHONY: clean
clean:
	rm -rf extracted/36 output/36 tarballs/psyq-36.tar.gz
