.SUFFIXES:
.SECONDARY:
SHELL := /bin/bash

URL := https://archive.org/download/ps1_sdks/Programmer%20Tools%20-%20Run-time%20Library%204.0%20%28USA%29%20%28Release%202.0%29_DTL-S2002_redump.zip

.PHONY: all
all: tarballs/psyq-40.tar.gz

tarballs/psyq-40.tar.gz: output/40
	@mkdir -p tarballs/
	tar -C $< -czf $@ .

output/40: extracted/40 wibo/build/wibo
	mkdir -p $@/BIN
	cp -r $</PSX/{LIB,INCLUDE} $@/
	rm -rf $@/LIB/OLD_LIBS $@/LIB/*.TXT $@/LIB/*.PDF
	cp $</PSSN/BIN/{ASMPSX,ASPSX,DUMPOBJ,PSYLIB,PSYLINK,PSYMAKE}.EXE $</GNU/{CC1PLPSX,CC1PSX,CCPSX,CPLUSPSX,CPPPSX}.EXE $</PSX/BIN/DMPSX.EXE $@/BIN/
	chmod a+rx $@/BIN/*
	touch $@/BIN/PSYQ.INI
	for exe in $@/BIN/*.EXE; do cp wibo/build/wibo $@/; cp wrapper.sh $@/`basename -s.EXE $$exe | tr A-Z a-z`; done

extracted/40: dl/40
	mkdir -p $@
	7z e -o$@ -i!'*Track 1*.bin' $<
	iat $@/*.bin $@/fs.iso
	-7z x -o$@ $@/fs.iso
	rename -d y/a-z/A-Z/ $@/*
	rename -d y/a-z/A-Z/ $@/*/*
	rename -d y/a-z/A-Z/ $@/*/*/*
	rm -f $@/*.bin $@/fs.iso

dl/40:
	mkdir -p dl
	wget --progress=dot:mega "$(URL)" -O $@

wibo/build/wibo:
	cmake wibo -B wibo/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0" -DCMAKE_FIND_LIBRARY_SUFFIXES=".a" -DCMAKE_EXE_LINKER_FLAGS="-static"
	make -C wibo/build

.PHONY: clean
clean:
	rm -rf extracted/40 output/40 tarballs/psyq-40.tar.gz
