on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: sudo apt-get install -y 7zip lhasa iat rename
            - uses: actions/checkout@v4
            - uses: actions/cache@v3
              with:
                  key: dl
                  path: dl
            - run: find .
            - run: make tarballs
            - uses: actions/upload-artifact@v4
              with:
                  path: tarballs/*.tar.gz
            - uses: ncipollo/release-action@v1
              with:
                  artifacts: tarballs/*.tar.gz
                  tag: 1.${{ github.ref }}
